name = "verb"
[http]
listen = "127.0.0.1:8080"

[data]
[data.db]
dsn = "mysql://root:123456@127.0.0.1:3308/verb"
log_level = "info"
idle_sec = 10
life_time = 10
connection = 100
logging = true
conn_timeout = 8
acquire_timeout = 8
